select
    activity_id,
    athlete_id,
    name as activity_name,
    activity_type,
    source,
    trainer,
    start_date_local,
    start_date_utc,
    moving_time_secs / 60.0 as moving_time_min,
    elapsed_time_secs / 60.0 as elapsed_time_min,
    nullif(training_load, 0) as training_load,
    ctl as ctl_intervals,
    atl as atl_intervals,
    trimp,
    avg_heartrate,
    max_heartrate,
    efficiency_factor,
    decoupling,
    intensity,
    avg_watts,
    nullif(weighted_avg_watts, 0) as weighted_avg_watts,
    ftp_at_activity,
    distance_m / 1000.0 as distance_km,
    elevation_gain_m,
    nullif(avg_speed_mps, 0) * 3.6 as avg_speed_kph,
    nullif(avg_cadence, 0) as avg_cadence,
    nullif(calories, 0) as calories,
    avg_temp_c,
    min_temp_c,
    max_temp_c,
    pulled_at
from {{ source('staging', 'intervals_activities_raw') }}