select
    activity_id,
    athlete_id,
    activity_name,
    activity_type,
    trainer,
    start_date_local,
    start_date_local::date as activity_date,
    to_char(start_date_local, 'Day') as day_of_week,
    moving_time_min,
    elapsed_time_min,
    distance_km,
    elevation_gain_m,
    avg_speed_kph,
    avg_cadence,
    avg_heartrate,
    max_heartrate,
    avg_watts,
    weighted_avg_watts,
    ftp_at_activity,
    intensity,
    efficiency_factor,
    decoupling,
    trimp,
    training_load,
    ctl_intervals,
    atl_intervals,
    calories,
    avg_temp_c,
    min_temp_c,
    max_temp_c
from {{ ref('stg_intervals_activities') }}
order by start_date_local desc